tunnel: c62175d5-40e4-4641-b89e-ba94339802a6
credentials-file: /etc/cloudflared/cert.pem

ingress:
  - hostname: sc.theangrygamershow.com
    service: http://172.19.0.3:8080
  - service: http_status:404